# Generated by Django 6.0 on 2026-01-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=40, verbose_name='Продукт')),
                ('image', models.ImageField(upload_to='products/', verbose_name='фото продукта')),
                ('description', models.TextField(verbose_name='описание продукта')),
                ('count', models.IntegerField(default=1, verbose_name='Колчиество:')),
                ('price', models.IntegerField(default=100, verbose_name='Цена:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Who_is_the_product_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.category')),
            ],
            options={
                'verbose_name': 'Список продуктов',
                'verbose_name_plural': 'Список продутов',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('🌟', '🌟'), ('🌟🌟', '🌟🌟'), ('🌟🌟🌟', '🌟🌟🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟'), ('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟')], default='🌟🌟🌟🌟🌟', max_length=100)),
                ('text', models.TextField(max_length=100, verbose_name='Отзыв')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('choice_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='product.products')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
