# Generated by Django 6.0 on 2025-12-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('type_product', models.CharField(choices=[('for_children', 'for_children'), ('for_adults', 'for_adults')], default='for_adults')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
