# Generated by Django 6.0 on 2025-12-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type_product',
        ),
        migrations.AddField(
            model_name='products',
            name='Who_is_the_product_for',
            field=models.CharField(choices=[('for_children', 'for_children'), ('for_adults', 'for_adults')], default='for_adults', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
