# Generated by Django 6.0 on 2026-01-08 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_products_type_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Список продуктов', 'verbose_name_plural': 'Список продутов'},
        ),
        migrations.AlterField(
            model_name='products',
            name='Who_is_the_product_for',
            field=models.CharField(choices=[('Для детей', 'Для детей'), ('Для взрослых', 'Для взрослых'), ('Для всех', 'Для всех')], default='Для всех', max_length=20, verbose_name='Котегория продукта:'),
        ),
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Колчиество:'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(verbose_name='описание продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='фото продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_product',
            field=models.CharField(max_length=40, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=100, verbose_name='Цена:'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('🌟', '🌟'), ('🌟🌟', '🌟🌟'), ('🌟🌟🌟', '🌟🌟🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟'), ('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟')], default='🌟🌟🌟🌟🌟', max_length=100)),
                ('text', models.TextField(max_length=100, verbose_name='Отзыв')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('choice_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='product.products')),
            ],
        ),
    ]
